/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.equivalencia.view;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author asilva
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        Color nova = new Color(0,0,0);
        getContentPane().setBackground(nova);
         
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/equivalencia/imagens/tela-icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoEquiv = new javax.swing.JButton();
        btnArea = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnEquivalencia = new javax.swing.JButton();
        btnUnidades = new javax.swing.JButton();
        btnPpc = new javax.swing.JButton();
        menPrincipal = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadUsuario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menCadPpc = new javax.swing.JMenuItem();
        menCadunidade = new javax.swing.JMenuItem();
        menCadArea = new javax.swing.JMenuItem();
        menCadGrupo = new javax.swing.JMenuItem();
        menEquiv = new javax.swing.JMenu();
        menEquivalencia = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menLogout = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenuItem();
        menAjuda = new javax.swing.JMenu();
        menFluxo = new javax.swing.JMenuItem();
        menManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIS Equivalência - SENAI Vitória - Tela Principal");
        setResizable(false);

        btnGrupoEquiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/grupo-equi-icon.png"))); // NOI18N
        btnGrupoEquiv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGrupoEquiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrupoEquiv.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnGrupoEquiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoEquivActionPerformed(evt);
            }
        });

        btnArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/area-icon.png"))); // NOI18N
        btnArea.setText("okay");
        btnArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArea.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/curso-b-icon.png"))); // NOI18N
        btnCurso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCurso.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnEquivalencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/equivalencia-b-icon.png"))); // NOI18N
        btnEquivalencia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEquivalencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquivalencia.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/unidade-icon.png"))); // NOI18N
        btnUnidades.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUnidades.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnPpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/ppc-icon.png"))); // NOI18N
        btnPpc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPpc.setMargin(new java.awt.Insets(0, 0, 0, 0));

        menCad.setText("Cadastro");
        menCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/user-icon.png"))); // NOI18N
        menCadUsuario.setText("Usuários");
        menCadUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menCadUsuarioMouseClicked(evt);
            }
        });
        menCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuarioActionPerformed(evt);
            }
        });
        menCad.add(menCadUsuario);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/curso-icon.png"))); // NOI18N
        jMenuItem2.setText("Cursos");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menCad.add(jMenuItem2);

        menCadPpc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/curso-icon.png"))); // NOI18N
        menCadPpc.setText("PPC");
        menCadPpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menCadPpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadPpcActionPerformed(evt);
            }
        });
        menCad.add(menCadPpc);

        menCadunidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/curso-icon.png"))); // NOI18N
        menCadunidade.setText("Unidades Curriculares");
        menCadunidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menCad.add(menCadunidade);

        menCadArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/tecnologica-icon.png"))); // NOI18N
        menCadArea.setText("Área Tecnológica");
        menCadArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menCadArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadAreaActionPerformed(evt);
            }
        });
        menCad.add(menCadArea);

        menCadGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/equivalencia-icon.png"))); // NOI18N
        menCadGrupo.setText("Grupo de Equivalência");
        menCadGrupo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menCadGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadGrupoActionPerformed(evt);
            }
        });
        menCad.add(menCadGrupo);

        menPrincipal.add(menCad);

        menEquiv.setText("Equivalencia");
        menEquiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menEquivalencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/equivalencia-icon.png"))); // NOI18N
        menEquivalencia.setText("Realizar Equivalência");
        menEquivalencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menEquivalencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEquivalenciaActionPerformed(evt);
            }
        });
        menEquiv.add(menEquivalencia);

        menPrincipal.add(menEquiv);

        menOpc.setText("Opções");
        menOpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOpcActionPerformed(evt);
            }
        });

        menLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/lougout-icon.png"))); // NOI18N
        menLogout.setText("Logout");
        menLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLogoutActionPerformed(evt);
            }
        });
        menOpc.add(menLogout);

        menSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/sair-icon.png"))); // NOI18N
        menSair.setText("Sair");
        menSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menOpc.add(menSair);

        menPrincipal.add(menOpc);

        menAjuda.setText("Ajuda");
        menAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menFluxo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/fluxo-icon.png"))); // NOI18N
        menFluxo.setText("Fluxo de Processo");
        menFluxo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menFluxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFluxoActionPerformed(evt);
            }
        });
        menAjuda.add(menFluxo);

        menManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/equivalencia/imagens/manual-icon.png"))); // NOI18N
        menManual.setText("Manual");
        menManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menAjuda.add(menManual);

        menPrincipal.add(menAjuda);

        setJMenuBar(menPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrupoEquiv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPpc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        btnArea.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCadAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadAreaActionPerformed
        this.dispose();
        TelaArea area = new TelaArea();
        area.setVisible(true);
    }//GEN-LAST:event_menCadAreaActionPerformed

    private void menFluxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFluxoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menFluxoActionPerformed

    private void menCadGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadGrupoActionPerformed
        this.dispose();
        TelaGrupoEquivalencia equivalencia = new TelaGrupoEquivalencia();
        equivalencia.setVisible(true);
    }//GEN-LAST:event_menCadGrupoActionPerformed

    private void menOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOpcActionPerformed
       
    }//GEN-LAST:event_menOpcActionPerformed

    private void menLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLogoutActionPerformed
        this.dispose();
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        
    }//GEN-LAST:event_menLogoutActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menSairActionPerformed

    private void menCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuarioActionPerformed
        this.dispose();
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
    }//GEN-LAST:event_menCadUsuarioActionPerformed

    private void menCadUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menCadUsuarioMouseClicked
        
    }//GEN-LAST:event_menCadUsuarioMouseClicked

    private void menCadPpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadPpcActionPerformed
        this.dispose();
        TelaPPC ppc = new TelaPPC();
        ppc.setVisible(true);
        
    }//GEN-LAST:event_menCadPpcActionPerformed

    private void btnGrupoEquivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoEquivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrupoEquivActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        TelaCursos curso = new TelaCursos();
        curso.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menEquivalenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEquivalenciaActionPerformed
        this.dispose();
        TelaEquivalencia equivalencia = new TelaEquivalencia();
        equivalencia.setVisible(true);
    }//GEN-LAST:event_menEquivalenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnEquivalencia;
    private javax.swing.JButton btnGrupoEquiv;
    private javax.swing.JButton btnPpc;
    private javax.swing.JButton btnUnidades;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menAjuda;
    public static javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadArea;
    private javax.swing.JMenuItem menCadGrupo;
    private javax.swing.JMenuItem menCadPpc;
    private javax.swing.JMenuItem menCadUsuario;
    private javax.swing.JMenuItem menCadunidade;
    private javax.swing.JMenu menEquiv;
    private javax.swing.JMenuItem menEquivalencia;
    private javax.swing.JMenuItem menFluxo;
    private javax.swing.JMenuItem menLogout;
    private javax.swing.JMenuItem menManual;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuBar menPrincipal;
    private javax.swing.JMenuItem menSair;
    // End of variables declaration//GEN-END:variables
}
